# 문제 분석
# 조회: ID, 이름, 주소, 냉동시설 여부
# 조건: 여부가 NULL이면 N으로 출력
# 순서: 창고ID 오름차순

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID;