# FIRST_HALF와 ICECREAM_INFO를 JOIN 해야 함
# FLAVOR를 출력하는 것이기 때문에, 어느 쪽으로 해도 상관 없으나 FIRST_HALF LEFT JOIN ICECREAM_INFO

SELECT 
    F.FLAVOR
FROM 
    FIRST_HALF AS F
    LEFT JOIN ICECREAM_INFO AS I
    ON F.FLAVOR = I.FLAVOR
WHERE
    F.TOTAL_ORDER > 3000
    AND I.INGREDIENT_TYPE = 'FRUIT_BASED'
ORDER BY
    TOTAL_ORDER DESC;